name: desafio_prominas_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_core: ^3.1.0
  firebase_analytics: ^11.0.1
  firebase_messaging: ^15.0.1
  dio: ^5.4.3+1
  get_it: ^7.7.0
  equatable: ^2.0.5
  fluttertoast: ^8.2.6
  shared_preferences: ^2.2.3
  flutter_initicon: ^3.0.1
  flutter_local_notifications: ^17.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_pdfview: ^1.2.7
  http: ^1.2.1
  path_provider: ^2.1.3
  flutter_cached_pdfview: ^0.4.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mortarboard.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/mortarboard.png
    - assets/images/person3d.png
    - assets/images/woman.png
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
